$(document).ready(function(){
    $(".owl-carousel").owlCarousel({
        autoplay:true,
        autoplaytimeout:3000,
        autoplayHoverPuse:true,
        loop:true,
        margin:10,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:5
            }
        }
    });
  });